name: Test Latest

on: [pull_request,workflow_dispatch]

jobs:
    pytests:
        runs-on: ubuntu-latest

        steps:
            - uses: szenius/set-timezone@v1.2
              with:
                timezoneLinux: "America/Los_Angeles"

            - uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
                architecture: 'x64'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements-dev.txt
                pip install pytest-md

            - name: Run pytest
              uses: pavelzw/pytest-action@v2
              with:
                verbose: true
                emoji: false
                job-summary: true
                custom-arguments: '-vvvs'
                click-to-expand: true
                report-title: 'Test Results'

    pylint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
                architecture: 'x64'

            - name: GitHub Action for pylint
              uses: cclauss/GitHub-Action-for-pylint@master
              with:
                args: "pip install -r requirements.txt ; pylint --disable=cyclic-import **/*.py"
